### PR TITLE
fix: log internal errors

### LINKED ISSUE #151: fix: add logging to rpc proxy
Currently there's no way to figure out why RPC Proxy is throwing HTTP 5xx to the user, unless it's 502. 
Logs are needed to be able to distinguish and understand the reason,

### PR DESCRIPTION
**Pull request by Rakowskiii**
# Description

Adding warn! logs for each unhandled error, so we have at least some ability to see what;s happening internally and take action.

Resolves #151 

## How Has This Been Tested?

Not tested, only adds logging.

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

File: src/error.rs [hunk 1]
```diff
@@ -101,11 +102,14 @@ impl IntoResponse for RpcError {
                 )),
             )
                 .into_response(),
-            _ => (
-                StatusCode::INTERNAL_SERVER_ERROR,
-                "Internal server error".to_string(),
-            )
-                .into_response(),
+            e => {
+                warn!("Internal server error: {}", e);
```
Comment (arein) [inline src/error.rs:106]:
```suggestion
                error!("Internal server error: {}", e);
```

**Review by arein — APPROVED** [review]
