### PR TITLE
fix: connection to sigv4 proxy

### LINKED ISSUE #188: bug: infra not deployed even when terraform changed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I changed environment variable in terraform, merged and deployed - the app got deployed, but the infra did not.

### Expected Behavior

When infra related files changed, infra should be deployed

### Steps To Reproduce

1. Create PR with terraform changes
2. Merge
3. Wait for deployment
4. Infra deployment will not run

### Environment

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Rakowskiii**
# Description

The rpc was at first trying to connect directly to prometheus instead of sigv4 proxy, and later was hitting proxy without proper header and workspace. This should fix it. Have no way of testing locally thought. This is still non-breaking change - if it fails, the app will default to static weights.

Resolves #188 

## How Has This Been Tested?

Terraform deployed to staging. 

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

File: src/providers/mod.rs [hunk 1]
```diff
@@ -39,23 +40,29 @@ pub struct ProviderRepository {
...
+            std::env::var("SIG_PROM_WORKSPACE_HEADER").unwrap_or("localhost:9090".into());
+
         Self {
             providers: HashMap::new(),
             ws_providers: HashMap::new(),
             weight_resolver: HashMap::new(),
             ws_weight_resolver: HashMap::new(),
             prometheus_client,
+            prometheus_workspace_header,
         }
```
Comment (arein) [inline src/providers/mod.rs:66]: unclear to me why that's needed?

**Review by arein — APPROVED** [review]

File: src/providers/mod.rs [hunk 2]
```diff
@@ -158,9 +165,15 @@ impl ProviderRepository {
     pub async fn update_weights(&self, metrics: &crate::Metrics) {
         info!("Updating weights");
 
+        let Ok(header_value) = HeaderValue::from_str(&self.prometheus_workspace_header) else {
```
Comment (Rakowskiii) [inline src/providers/mod.rs:168]: @arein the header is used here to properly call `sigv4proxy` using `prometheus_client`
