### PR TITLE
fix: checked mul

### LINKED ISSUE #230: Panic on multiplication
After the outage we accumulated so many failures that square of them went out of bounds for multiplication.
Needed change to checked mul

### PR DESCRIPTION
**Pull request by Rakowskiii**
# Description

After downtime of metrics we accumulated a lot of failures -> we overflowed on squaring failures count. 
Changed from u32 -> u64 and added checked multiplication.

Resolves #230 

## How Has This Been Tested?

Ran test.

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

File: src/providers/weights.rs [hunk 1]
```diff
@@ -62,17 +62,27 @@ const PERFECT_RATIO: f64 = 1.0;
...
-    chain_availability: &Availability,
-) -> u32 {
+    chain_availability: Availability,
+) -> u64 {
     let Availability(provider_success, provider_failure) = provider_availability;
 
     // Sum failed and successful calls for provider
-    let provider_total = provider_success + provider_failure * provider_failure;
+    let Some(provider_failures_squared) = provider_failure.checked_mul(provider_failure) else {
+        // 1 is minimal value for chein weight
```
Comment (chris13524) [inline src/providers/weights.rs:71]: Do we want a minimal value or a maximal value? Min would result in thrashing, no?
```suggestion
        // 1 is minimal value for chain weight
```

Do we really expect this to overflow given the increase to u64? Is there a better way to handle very large numbers?

Comment (Rakowskiii) [reply src/providers/weights.rs:71]: Not sure what would be the best way to handle this, this is mainly a hotfix, as I want to get it back online.
https://github.com/WalletConnect/rpc-proxy/issues/232
here's the task for future improvements

File: src/providers/weights.rs [hunk 2]
```diff
@@ -62,17 +62,27 @@ const PERFECT_RATIO: f64 = 1.0;
...
+        return 1;
```
[the remark this answers is not in the document]
Comment (Rakowskiii) [reply src/providers/weights.rs:72]: We actually need this return, as this should return from the whole function, it's not final value of this block expression

File: src/providers/weights.rs (hunk 1 above)
Comment (chris13524) [reply src/providers/weights.rs:71]: Actually, defaulting to 1 will result in over-prioritizing this provider, no? So 1 is definitely worse than defaulting to `provider_failure`?

Comment (chris13524) [reply src/providers/weights.rs:71]: It's also possible we hit an overflow down below:
```rust
let provider_total = provider_success + provider_failures_squared;
```

Comment (Rakowskiii) [reply src/providers/weights.rs:71]: But this 1 is not a value we give to provider_squared. It's value of weight (minial possible weight) we give to this

Comment (Rakowskiii) [reply src/providers/weights.rs:71]: Hence the return function

Comment (chris13524) [reply src/providers/weights.rs:71]: What happens if we set the weight of a provider to 0? We should do that if availability goes below e.g. 90%.

Comment (Rakowskiii) [reply src/providers/weights.rs:71]: I'd return to the edge case on addition with the other issue, for now just want to get it back online, and this should work in 99,9% of cases

Comment (Rakowskiii) [reply src/providers/weights.rs:71]: If we set it to 0 we will disable the provider. And actually I think this is what we should do

**Review by chris13524 — APPROVED** [review]
